// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/arithops": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "endpoint to execute arithmetic operations",
                "parameters": [
                    {
                        "description": "Aithmetic Operation",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.payloadSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.responseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.responseSchema"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.payloadSchema": {
            "type": "object",
            "properties": {
                "first_number": {
                    "type": "number"
                },
                "operation": {
                    "description": "Operation must be one of 'ADD', 'SUBTRACT', 'MULTIPLY', and 'DIVIDE'\"",
                    "type": "string"
                },
                "second_number": {
                    "type": "number"
                }
            }
        },
        "main.responseSchema": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
