services:
  db:
    container_name: db
    image: mysql
    restart: always
    secrets:
      - secrets
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=flask_app
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend-db

  backend:
    container_name: backend
    build: .
    entrypoint: /code/entrypoint.sh
    ports:
      - 8000:8000
    secrets:
      - secrets
    environment:
      - FLASK_APP=backend/app
      - FLASK_DEBUG=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_HOST=db
      - SECRET=mJhslfdJSD9248445Mmndsasdm
    depends_on:
      - db
    networks:
      - backend-db

networks:
  backend-db:
    driver: bridge

volumes:
  db:


secrets:
  secrets:
    file: secrets
